language: ruby
before_install:
  - gem install bundler
matrix:
  include:
    - rvm: 1.9.3
      gemfile: "test/gemfiles/Gemfile.ruby-1.9"
    - rvm: 2.0.1
      gemfile: Gemfile
    - rvm: 2.3.1
      gemfile: Gemfile
